"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 20:08:23.587748
"""
from alembic import op
import sqlalchemy as sa
import tape.db


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_log',
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('sent_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('alert_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_log_account'), ['account'], unique=False)

    op.create_table('bias_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('asset', sa.String(length=8), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=8), nullable=False),
    sa.Column('events_used', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bias_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bias_snapshots_asset'), ['asset'], unique=False)
        batch_op.create_index(batch_op.f('ix_bias_snapshots_ts'), ['ts'], unique=False)

    op.create_table('cash_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('book', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('ts', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('amount', tape.db.ExactDecimal(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account', 'source', 'book', 'external_id', name='uq_cash_flow_identity')
    )
    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_flows_account'), ['account'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_flows_book'), ['book'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_flows_ts'), ['ts'], unique=False)

    op.create_table('connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('tz', sa.String(length=64), nullable=False),
    sa.Column('secret', sa.Text(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('last_sync_at', tape.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=16), nullable=False),
    sa.Column('last_new', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connections_account'), ['account'], unique=False)

    op.create_table('econ_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('ts', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('impact', sa.String(length=8), nullable=False),
    sa.Column('forecast', sa.String(length=32), nullable=False),
    sa.Column('previous', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_econ_event')
    )
    with op.batch_alter_table('econ_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_econ_events_ts'), ['ts'], unique=False)

    op.create_table('equity_snapshots',
    sa.Column('book', sa.String(length=64), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('ts', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('balance', tape.db.ExactDecimal(length=64), nullable=False),
    sa.Column('equity', tape.db.ExactDecimal(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('book')
    )
    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equity_snapshots_account'), ['account'], unique=False)

    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('book', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('ts', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', tape.db.ExactDecimal(length=64), nullable=False),
    sa.Column('price', tape.db.ExactDecimal(length=64), nullable=False),
    sa.Column('contract_size', tape.db.ExactDecimal(length=64), nullable=False),
    sa.Column('fee', tape.db.ExactDecimal(length=64), nullable=False),
    sa.Column('broker_pnl', tape.db.ExactDecimal(length=64), nullable=True),
    sa.Column('stop_loss', tape.db.ExactDecimal(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account', 'source', 'book', 'external_id', name='uq_fill_identity')
    )
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fills_account'), ['account'], unique=False)
        batch_op.create_index(batch_op.f('ix_fills_book'), ['book'], unique=False)
        batch_op.create_index(batch_op.f('ix_fills_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_fills_ts'), ['ts'], unique=False)

    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('new', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('published_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('cluster_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_articles_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_published_at'), ['published_at'], unique=False)

    op.create_table('news_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('occurred_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('place', sa.String(length=128), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('impacts', sa.JSON(), nullable=False),
    sa.Column('novelty', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sources', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=8), nullable=False),
    sa.Column('ts', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset', 'ts', name='uq_price')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prices_asset'), ['asset'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_ts'), ['ts'], unique=False)

    op.create_table('prop_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('book', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('initial_balance', tape.db.ExactDecimal(length=64), nullable=False),
    sa.Column('daily_loss_pct', tape.db.ExactDecimal(length=64), nullable=False),
    sa.Column('max_drawdown_pct', tape.db.ExactDecimal(length=64), nullable=False),
    sa.Column('drawdown_type', sa.String(length=10), nullable=False),
    sa.Column('profit_target_pct', tape.db.ExactDecimal(length=64), nullable=True),
    sa.Column('day_tz', sa.String(length=64), nullable=False),
    sa.Column('updated_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account', 'book', name='uq_prop_account_book')
    )
    with op.batch_alter_table('prop_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prop_accounts_account'), ['account'], unique=False)

    op.create_table('quotes',
    sa.Column('asset', sa.String(length=8), nullable=False),
    sa.Column('ts', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('asset')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('created_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('facts_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_account'), ['account'], unique=False)

    op.create_table('setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('created_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account', 'name', name='uq_setup_name')
    )
    with op.batch_alter_table('setups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setups_account'), ['account'], unique=False)

    op.create_table('user_settings',
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('weekly_report', sa.Boolean(), nullable=False),
    sa.Column('prop_alerts', sa.Boolean(), nullable=False),
    sa.Column('last_weekly_at', tape.db.UtcDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('account')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('position_key', sa.String(length=32), nullable=False),
    sa.Column('setup_id', sa.Integer(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('mistakes', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('initial_stop', tape.db.ExactDecimal(length=64), nullable=True),
    sa.Column('updated_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['setup_id'], ['setups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account', 'position_key', name='uq_journal_position')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_account'), ['account'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_position_key'), ['position_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_position_key'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_account'))

    op.drop_table('journal_entries')
    op.drop_table('user_settings')
    with op.batch_alter_table('setups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setups_account'))

    op.drop_table('setups')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_account'))

    op.drop_table('reviews')
    op.drop_table('quotes')
    with op.batch_alter_table('prop_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prop_accounts_account'))

    op.drop_table('prop_accounts')
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prices_ts'))
        batch_op.drop_index(batch_op.f('ix_prices_asset'))

    op.drop_table('prices')
    with op.batch_alter_table('news_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_events_occurred_at'))

    op.drop_table('news_events')
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_articles_cluster_id'))

    op.drop_table('news_articles')
    op.drop_table('imports')
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fills_ts'))
        batch_op.drop_index(batch_op.f('ix_fills_symbol'))
        batch_op.drop_index(batch_op.f('ix_fills_book'))
        batch_op.drop_index(batch_op.f('ix_fills_account'))

    op.drop_table('fills')
    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equity_snapshots_account'))

    op.drop_table('equity_snapshots')
    with op.batch_alter_table('econ_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_econ_events_ts'))

    op.drop_table('econ_events')
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connections_account'))

    op.drop_table('connections')
    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_flows_ts'))
        batch_op.drop_index(batch_op.f('ix_cash_flows_book'))
        batch_op.drop_index(batch_op.f('ix_cash_flows_account'))

    op.drop_table('cash_flows')
    with op.batch_alter_table('bias_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bias_snapshots_ts'))
        batch_op.drop_index(batch_op.f('ix_bias_snapshots_asset'))

    op.drop_table('bias_snapshots')
    with op.batch_alter_table('alert_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_log_account'))

    op.drop_table('alert_log')
    # ### end Alembic commands ###
