"""ai credentials

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 20:44:59.412763
"""
from alembic import op
import sqlalchemy as sa
import tape.db


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_credentials',
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('updated_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('account')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_credentials')
    # ### end Alembic commands ###
