"""brief and mcp tokens

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 21:01:28.216649
"""
from alembic import op
import sqlalchemy as sa
import tape.db


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brief_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=96), nullable=False),
    sa.Column('sent_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brief_id', 'target', name='uq_brief_delivery')
    )
    with op.batch_alter_table('brief_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brief_deliveries_brief_id'), ['brief_id'], unique=False)

    op.create_table('brief_subscriptions',
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=32), nullable=True),
    sa.Column('telegram_name', sa.String(length=80), nullable=False),
    sa.Column('discord_webhook', sa.Text(), nullable=True),
    sa.Column('link_code', sa.String(length=32), nullable=True),
    sa.Column('link_expires', tape.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('updated_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('account'),
    sa.UniqueConstraint('link_code')
    )
    with op.batch_alter_table('brief_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brief_subscriptions_telegram_chat_id'), ['telegram_chat_id'], unique=False)

    op.create_table('briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('created_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day')
    )
    op.create_table('mcp_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('hint', sa.String(length=16), nullable=False),
    sa.Column('created_at', tape.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', tape.db.UtcDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('mcp_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_tokens_account'), ['account'], unique=False)

    op.create_table('worker_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_state')
    with op.batch_alter_table('mcp_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_tokens_account'))

    op.drop_table('mcp_tokens')
    op.drop_table('briefs')
    with op.batch_alter_table('brief_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brief_subscriptions_telegram_chat_id'))

    op.drop_table('brief_subscriptions')
    with op.batch_alter_table('brief_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brief_deliveries_brief_id'))

    op.drop_table('brief_deliveries')
    # ### end Alembic commands ###
